# Common tool shortcuts
alias g="git"
alias lg="lazygit"
alias nv="nvim"
alias tm="tmux"
alias zl="zellij"
alias mk="make"
alias py="python"
alias ve="virtualenv"
alias rb="ruby"
alias ra="rails"
alias tf="terraform"
alias pn="pnpm"
alias cl="claude"
alias gm="gemini"
alias dc="docker compose"
alias nvs="nvidia-smi"
