# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

quitOnTopLevelReturn: true

keybinding:
  universal:
    quit: "q"
    return: "<esc>"

customCommands:
  - key: t
    command: geminicommit
    context: files
    description: "commit with Gemini AI"
    loadingText: "generating commit message with Gemini AI"
    output: terminal

os:
  editPreset: 'nvim'
  edit: "nvr -l --remote {{filename}} && nvr -c 'wincmd p | close'"
  editAtLine: "nvr -l --remote +{{line}} {{filename}} && nvr -c 'wincmd p | close'"
