# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"


[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.z]
github = "rupa/z"
apply = ["defer"]

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
apply = ["defer"]

[plugins.delta]
github = "dandavison/delta"
apply = ["defer"]

[plugins.zsh-replace-multiple-dots]
github = "momo-lab/zsh-replace-multiple-dots"
apply = ["defer"]

[plugins.forgit]
github = "wfxr/forgit"
apply = ["defer"]

[plugins.tealdeer]
github = "dbrgn/tealdeer"
apply = ["defer"]

[plugins.navi]
github = "denisidoro/navi"
apply = ["defer"]

[plugins.zeno_zsh]
github = 'yuki-yano/zeno.zsh'
apply = ["defer"]

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"

[plugins.cclog]
github = "choplin/cclog"

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"

[plugins.zsh-system-clipboard]
github = "kutsan/zsh-system-clipboard"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]

[plugins.fzf]
github = 'junegunn/fzf'
apply = ['fzf-install']

#[plugins.starship]
#github = "starship/starship"

#[plugins.powerlevel10k]
#github = "romkatv/powerlevel10k"
#apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
fzf-install = "{{ dir }}/install --bin > /dev/null \n path=($path {{ dir }}/bin(N-/))\n"
